/*
 * (C) Copyright IBM Corp. 2020
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package io.github.linuxforhealth.api;

import java.util.Map;

/**
 * Resource value holds the result of Resource evaluation.
 * 
 *
 * @author pbhallam
 */
public interface ResourceValue {

  /**
   * Represents the Resource - Map
   * 
   * @return Map where key is the field name and value is result of that field generated by
   *         evaluating the expression for that field.
   */
  Map<String, Object> getResource();

  /**
   * FHIR Resource Type Example: Observation/Patient
   * 
   * @return String
   */
  String getFHIRResourceType();

  /**
   * If the resource map is empty or null, this method should return True.
   * 
   * @return - True if resource map is empty or null.
   */
  boolean isEmpty();


}
